---
- include_tasks:        'tasks/common/install_packages.yml'
- include_tasks:        'tasks/common/create_files.yml'
- include_tasks:        'tasks/common/install_files.yml'
- include_tasks:        'tasks/common/template_files.yml'
- include_tasks:        'tasks/common/symlinks.yml'
- include_tasks:        'tasks/common/start_services.yml'
  when:                 install_packages_result.changed
                        or install_files_result.changed
- include_tasks:        'tasks/common/restart_services.yml'
  when:                 template_files_result.changed
                        or symlinks_result.changed
                        or install_packages_result.changed
- include_tasks:        'tasks/common/shell_commands.yml'
