---
- include_tasks:        '../tasks/install_packages.yml'
- include_tasks:        '../tasks/create_files.yml'
- include_tasks:        '../tasks/install_files.yml'
- include_tasks:        '../tasks/template_files.yml'
- include_tasks:        '../tasks/symlinks.yml'
- include_tasks:        '../tasks/start_services.yml'
  when:                 install_packages_result.changed
                        or install_files_result.changed
- include_tasks:        '../tasks/restart_services.yml'
  when:                 template_files_result.changed
                        or symlinks_result.changed
                        or install_packages_result.changed
- include_tasks:        '../tasks/shell_commands.yml'
